//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSCADA.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeSCADA.Designer.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归档.
        /// </summary>
        internal static string ArchiverItemName {
            get {
                return ResourceManager.GetString("ArchiverItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定布尔标签.
        /// </summary>
        internal static string BooleanBindingPanelName {
            get {
                return ResourceManager.GetString("BooleanBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; xmlns:s=&quot;clr-namespace:System;assembly=mscorlib&quot; &gt;
        ///      &lt;Viewbox&gt;
        ///        &lt;Border BorderThickness=&quot;1,1,1,1&quot; BorderBrush=&quot;#FF0000FF&quot; Name=&quot;bdr&quot;&gt;
        ///          &lt;StackPanel Orientation=&quot;Vertical&quot;&gt;
        ///            &lt;TextBlock Text=&quot;{Binding Path=Name}&quot; Name=&quot;txt1&quot; Margin=&quot;0,0,10,0&quot; ToolTip=&quot;{Binding Path=Type}&quot; /&gt;
        ///            &lt;TextBlock Text=&quot;{Binding Path=Value}&quot; Name=&quot;txt2&quot; Margi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChannelDefaultTemplate {
            get {
                return ResourceManager.GetString("ChannelDefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驱动.
        /// </summary>
        internal static string ChannelsItemName {
            get {
                return ResourceManager.GetString("ChannelsItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox Tool.
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载查看.
        /// </summary>
        internal static string CommandCheckForUpdatesDescription {
            get {
                return ResourceManager.GetString("CommandCheckForUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看更新.
        /// </summary>
        internal static string CommandCheckForUpdatesName {
            get {
                return ResourceManager.GetString("CommandCheckForUpdatesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据绑定向导.
        /// </summary>
        internal static string CommandCommonBindingName {
            get {
                return ResourceManager.GetString("CommandCommonBindingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string CommandContextHelp {
            get {
                return ResourceManager.GetString("CommandContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string CommandCopyDescription {
            get {
                return ResourceManager.GetString("CommandCopyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string CommandCopyName {
            get {
                return ResourceManager.GetString("CommandCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        internal static string CommandCutDescription {
            get {
                return ResourceManager.GetString("CommandCutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        internal static string CommandCutName {
            get {
                return ResourceManager.GetString("CommandCutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成组选择.
        /// </summary>
        internal static string CommandGroupDescription {
            get {
                return ResourceManager.GetString("CommandGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成组选择.
        /// </summary>
        internal static string CommandGroupName {
            get {
                return ResourceManager.GetString("CommandGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        internal static string CommandPasteDescription {
            get {
                return ResourceManager.GetString("CommandPasteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        internal static string CommandPasteName {
            get {
                return ResourceManager.GetString("CommandPasteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        internal static string CommandRedoDescription {
            get {
                return ResourceManager.GetString("CommandRedoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        internal static string CommandRedoName {
            get {
                return ResourceManager.GetString("CommandRedoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        internal static string CommandUndoDescription {
            get {
                return ResourceManager.GetString("CommandUndoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        internal static string CommandUndoName {
            get {
                return ResourceManager.GetString("CommandUndoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解组.
        /// </summary>
        internal static string CommandUngroupDescription {
            get {
                return ResourceManager.GetString("CommandUngroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解组.
        /// </summary>
        internal static string CommandUngroupName {
            get {
                return ResourceManager.GetString("CommandUngroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动脚本语法验证.
        /// </summary>
        internal static string CommandValidateDescription {
            get {
                return ResourceManager.GetString("CommandValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语法检查.
        /// </summary>
        internal static string CommandValidateName {
            get {
                return ResourceManager.GetString("CommandValidateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML浏览器.
        /// </summary>
        internal static string CommandXamlViewDescription {
            get {
                return ResourceManager.GetString("CommandXamlViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML浏览器.
        /// </summary>
        internal static string CommandXamlViewName {
            get {
                return ResourceManager.GetString("CommandXamlViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移到后面.
        /// </summary>
        internal static string CommandZMoveBottomDescription {
            get {
                return ResourceManager.GetString("CommandZMoveBottomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移到后面.
        /// </summary>
        internal static string CommandZMoveBottomName {
            get {
                return ResourceManager.GetString("CommandZMoveBottomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移到前面.
        /// </summary>
        internal static string CommandZMoveTopDescription {
            get {
                return ResourceManager.GetString("CommandZMoveTopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移到前面.
        /// </summary>
        internal static string CommandZMoveTopName {
            get {
                return ResourceManager.GetString("CommandZMoveTopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 适合窗口.
        /// </summary>
        internal static string CommandZoomDescription {
            get {
                return ResourceManager.GetString("CommandZoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放大.
        /// </summary>
        internal static string CommandZoomInDescription {
            get {
                return ResourceManager.GetString("CommandZoomInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放大.
        /// </summary>
        internal static string CommandZoomInName {
            get {
                return ResourceManager.GetString("CommandZoomInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 适合窗口.
        /// </summary>
        internal static string CommandZoomName {
            get {
                return ResourceManager.GetString("CommandZoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩小.
        /// </summary>
        internal static string CommandZoomOutDescription {
            get {
                return ResourceManager.GetString("CommandZoomOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩小.
        /// </summary>
        internal static string CommandZoomOutName {
            get {
                return ResourceManager.GetString("CommandZoomOutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All vector graphics (*.xaml;*.svg)|*.xaml;*.svg|XAML  files (*.xaml)|*.xaml|svg files (*.svg)|*.svg|All files (*.*)|*.*.
        /// </summary>
        internal static string FileImportDialogFilter {
            get {
                return ResourceManager.GetString("FileImportDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeSCADA 2 files (*.fs2)|*.fs2|All files (*.*)|*.*.
        /// </summary>
        internal static string FileOpenDialogFilter {
            get {
                return ResourceManager.GetString("FileOpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择对象（线条，矩形，椭圆）.
        /// </summary>
        internal static string HelperSelectingToolTooltip {
            get {
                return ResourceManager.GetString("HelperSelectingToolTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设计器.
        /// </summary>
        internal static string MainWindowName {
            get {
                return ResourceManager.GetString("MainWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] - 设计.
        /// </summary>
        internal static string MainWindowNameEx {
            get {
                return ResourceManager.GetString("MainWindowNameEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多态文本.
        /// </summary>
        internal static string MultiTextBindingPanelName {
            get {
                return ResourceManager.GetString("MultiTextBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定数值标签.
        /// </summary>
        internal static string NumericBindingPanelName {
            get {
                return ResourceManager.GetString("NumericBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定到C#脚本函数.
        /// </summary>
        internal static string NumExpressionBindingPanelName {
            get {
                return ResourceManager.GetString("NumExpressionBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 媒体文件|*.gif;*.BMP;*.PNG;*.JPEG;*.JPG;*.TIFF|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenMediaDialogFilter {
            get {
                return ResourceManager.GetString("OpenMediaDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        internal static string ProjectContextMenuOpen {
            get {
                return ResourceManager.GetString("ProjectContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string ProjectContextMenuRemove {
            get {
                return ResourceManager.GetString("ProjectContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名.
        /// </summary>
        internal static string ProjectContextMenuRename {
            get {
                return ResourceManager.GetString("ProjectContextMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阈值颜色表.
        /// </summary>
        internal static string RangeSolidBrushBindingPanelName {
            get {
                return ResourceManager.GetString("RangeSolidBrushBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模式.
        /// </summary>
        internal static string SchemasItemName {
            get {
                return ResourceManager.GetString("SchemasItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定到C#脚本函数.
        /// </summary>
        internal static string ScriptExpressionBindingPanelName {
            get {
                return ResourceManager.GetString("ScriptExpressionBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脚本.
        /// </summary>
        internal static string ScriptsItemName {
            get {
                return ResourceManager.GetString("ScriptsItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定颜色到标签.
        /// </summary>
        internal static string SolidColorBindingPanelName {
            get {
                return ResourceManager.GetString("SolidColorBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符串值绑定.
        /// </summary>
        internal static string StringBindingPanelName {
            get {
                return ResourceManager.GetString("StringBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值绑定.
        /// </summary>
        internal static string StringValueBindingPanelName {
            get {
                return ResourceManager.GetString("StringValueBindingPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本显示（html支持）.
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动作.
        /// </summary>
        internal static string ToolActionEdit {
            get {
                return ResourceManager.GetString("ToolActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按钮.
        /// </summary>
        internal static string ToolButton {
            get {
                return ResourceManager.GetString("ToolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格.
        /// </summary>
        internal static string ToolChart {
            get {
                return ResourceManager.GetString("ToolChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控件.
        /// </summary>
        internal static string ToolContentControl {
            get {
                return ResourceManager.GetString("ToolContentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控件.
        /// </summary>
        internal static string ToolControlsGroupName {
            get {
                return ResourceManager.GetString("ToolControlsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        internal static string ToolEditorGroupName {
            get {
                return ResourceManager.GetString("ToolEditorGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 椭圆.
        /// </summary>
        internal static string ToolEllipse {
            get {
                return ResourceManager.GetString("ToolEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF图形工具.
        /// </summary>
        internal static string ToolGrphicsGroupName {
            get {
                return ResourceManager.GetString("ToolGrphicsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF图形工具.
        /// </summary>
        internal static string ToolImageControl {
            get {
                return ResourceManager.GetString("ToolImageControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线条.
        /// </summary>
        internal static string ToolPolyline {
            get {
                return ResourceManager.GetString("ToolPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进度条.
        /// </summary>
        internal static string ToolProgressbar {
            get {
                return ResourceManager.GetString("ToolProgressbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矩形.
        /// </summary>
        internal static string ToolRectangle {
            get {
                return ResourceManager.GetString("ToolRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滚动条.
        /// </summary>
        internal static string ToolScrollbar {
            get {
                return ResourceManager.GetString("ToolScrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        internal static string ToolSelection {
            get {
                return ResourceManager.GetString("ToolSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滑动条.
        /// </summary>
        internal static string ToolSlider {
            get {
                return ResourceManager.GetString("ToolSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本显示（html支持）.
        /// </summary>
        internal static string ToolTextbox {
            get {
                return ResourceManager.GetString("ToolTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开关按钮.
        /// </summary>
        internal static string ToolToggleButton {
            get {
                return ResourceManager.GetString("ToolToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDemo.
        /// </summary>
        internal static string UnsavedProjectName {
            get {
                return ResourceManager.GetString("UnsavedProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewMode.
        /// </summary>
        internal static string UntitledSchema {
            get {
                return ResourceManager.GetString("UntitledSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script_.
        /// </summary>
        internal static string UntitledScript {
            get {
                return ResourceManager.GetString("UntitledScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络连接失败: {0}.
        /// </summary>
        internal static string UpdatesFailToCheckForNewVersion {
            get {
                return ResourceManager.GetString("UpdatesFailToCheckForNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有最新的FreeSCADA版本.
        /// </summary>
        internal static string UpdatesHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("UpdatesHaveTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeSCADA新版本可用。你要去网站下载吗？.
        /// </summary>
        internal static string UpdatesNewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdatesNewVersionAvailable", resourceCulture);
            }
        }
    }
}
